required-players: 2
minimum-players: 2
countdown-seconds: 30
lobby-spawm:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  1:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0